# Generated by Django 4.2.11 on 2026-03-26 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
        ('locations', '0001_initial'),
        ('rumors', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rumorclaim',
            options={'ordering': ['-created_at'], 'verbose_name': 'Rumor Claim', 'verbose_name_plural': 'Rumor Claims'},
        ),
        migrations.AlterModelOptions(
            name='rumorevidence',
            options={'verbose_name': 'Rumor Evidence', 'verbose_name_plural': 'Rumor Evidence'},
        ),
        migrations.AlterModelOptions(
            name='rumorverdict',
            options={'ordering': ['-verified_at'], 'verbose_name': 'Rumor Verdict', 'verbose_name_plural': 'Rumor Verdicts'},
        ),
        migrations.AlterField(
            model_name='rumorclaim',
            name='area',
            field=models.ForeignKey(blank=True, help_text='Area inferred or chosen for this rumor.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.area'),
        ),
        migrations.AlterField(
            model_name='rumorclaim',
            name='city',
            field=models.ForeignKey(blank=True, help_text='City inferred or chosen for this rumor.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.city'),
        ),
        migrations.AlterField(
            model_name='rumorclaim',
            name='extracted_entities',
            field=models.JSONField(blank=True, default=list, help_text='Parsed entities or keywords used during verification.'),
        ),
        migrations.AlterField(
            model_name='rumorclaim',
            name='pincode',
            field=models.CharField(blank=True, help_text='Optional pincode for location matching.', max_length=12),
        ),
        migrations.AlterField(
            model_name='rumorclaim',
            name='text',
            field=models.TextField(help_text='Original rumor text, WhatsApp message, or claim submitted by the user.'),
        ),
        migrations.AlterField(
            model_name='rumorevidence',
            name='note',
            field=models.CharField(blank=True, help_text='Short note describing why this evidence matters.', max_length=255),
        ),
        migrations.AlterField(
            model_name='rumorevidence',
            name='raw_item',
            field=models.ForeignKey(blank=True, help_text='Linked raw source item, if available.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.rawingestitem'),
        ),
        migrations.AlterField(
            model_name='rumorevidence',
            name='source_name',
            field=models.CharField(blank=True, help_text='Display name of the supporting source.', max_length=120),
        ),
        migrations.AlterField(
            model_name='rumorevidence',
            name='story',
            field=models.ForeignKey(blank=True, help_text='Linked normalized story, if available.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.story'),
        ),
        migrations.AlterField(
            model_name='rumorevidence',
            name='url',
            field=models.URLField(blank=True, help_text='Direct evidence URL shown to the user.'),
        ),
        migrations.AlterField(
            model_name='rumorverdict',
            name='confidence',
            field=models.PositiveSmallIntegerField(default=0, help_text='System confidence from 0 to 100.'),
        ),
        migrations.AlterField(
            model_name='rumorverdict',
            name='explanation',
            field=models.TextField(help_text='Human-readable explanation for the verdict.'),
        ),
        migrations.AlterField(
            model_name='rumorverdict',
            name='official_link',
            field=models.URLField(blank=True, help_text='Most relevant official clarification or confirmation link.'),
        ),
        migrations.AlterField(
            model_name='rumorverdict',
            name='verdict',
            field=models.CharField(choices=[('verified', 'Verified'), ('unconfirmed', 'Unconfirmed'), ('false_debunked', 'False - Debunked')], help_text='Final classification returned to the user.', max_length=20),
        ),
    ]
