# Generated by Django 4.2.11 on 2026-03-26 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='intelligencerun',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='intelligencerun',
            name='model_name',
            field=models.CharField(blank=True, help_text='Exact model identifier used for this run.', max_length=64),
        ),
        migrations.AddField(
            model_name='intelligencerun',
            name='provider',
            field=models.CharField(blank=True, help_text='AI or rules engine used for this run.', max_length=32),
        ),
    ]
