# Generated by Django 4.2.11 on 2026-03-26 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawIngestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, max_length=255)),
                ('url', models.URLField()),
                ('headline', models.CharField(max_length=500)),
                ('raw_body', models.TextField(blank=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('checksum', models.CharField(max_length=64)),
                ('normalized_key', models.CharField(blank=True, db_index=True, max_length=255)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_items', to='sources.source')),
            ],
            options={
                'ordering': ['-published_at', '-fetched_at'],
                'unique_together': {('source', 'url', 'checksum')},
            },
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=500)),
                ('summary', models.TextField(blank=True)),
                ('impact_summary', models.TextField(blank=True)),
                ('action_summary', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('supply_crisis', 'Supply Crisis'), ('weather', 'Weather'), ('civil_unrest', 'Civil Unrest'), ('price_surge', 'Price Surge'), ('health', 'Health'), ('general', 'General')], default='general', max_length=32)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=16)),
                ('status', models.CharField(choices=[('verified', 'Verified'), ('unconfirmed', 'Unconfirmed'), ('debunked', 'Debunked')], default='unconfirmed', max_length=16)),
                ('priority_score', models.PositiveSmallIntegerField(default=0)),
                ('confidence_score', models.PositiveSmallIntegerField(default=0)),
                ('official_resource_url', models.URLField(blank=True)),
                ('source_count', models.PositiveSmallIntegerField(default=0)),
                ('normalized_key', models.CharField(max_length=255, unique=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-priority_score', '-published_at', '-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='StoryTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='news.story')),
            ],
            options={
                'unique_together': {('story', 'name')},
            },
        ),
        migrations.CreateModel(
            name='StorySourceEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('raw_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_links', to='news.rawingestitem')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='news.story')),
            ],
            options={
                'unique_together': {('story', 'raw_item')},
            },
        ),
        migrations.CreateModel(
            name='StoryLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pincode', models.CharField(blank=True, max_length=12)),
                ('relevance_score', models.PositiveSmallIntegerField(default=50)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.area')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.city')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.country')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.state')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='news.story')),
            ],
            options={
                'unique_together': {('story', 'country', 'state', 'city', 'area', 'pincode')},
            },
        ),
    ]
