HYDERABAD_REFERENCE_DATA = {
    "country": {"name": "India", "code": "IN"},
    "state": {"name": "Telangana", "code": "TS"},
    "city": {"name": "Hyderabad"},
    "areas": [
        {"name": "Banjara Hills", "pincode": "500034"},
        {"name": "Jubilee Hills", "pincode": "500033"},
        {"name": "Secunderabad", "pincode": "500003"},
        {"name": "Madhapur", "pincode": "500081"},
        {"name": "Kukatpally", "pincode": "500072"},
    ],
}


SOURCE_SEED_DATA = [
    {
        "name": "The Hindu",
        "kind": "rss",
        "base_url": "https://www.thehindu.com",
        "feed_url": "https://www.thehindu.com/news/national/feeder/default.rss",
        "credibility_tier": "tier_1",
        "coverage_scope": "national",
        "is_official": False,
    },
    {
        "name": "Times of India Hyderabad",
        "kind": "rss",
        "base_url": "https://timesofindia.indiatimes.com",
        "feed_url": "https://timesofindia.indiatimes.com/rssfeeds/-2128816011.cms",
        "credibility_tier": "tier_1",
        "coverage_scope": "local",
        "is_official": False,
    },
    {
        "name": "NDTV",
        "kind": "rss",
        "base_url": "https://www.ndtv.com",
        "feed_url": "https://feeds.feedburner.com/NDTV-LatestNews",
        "credibility_tier": "tier_1",
        "coverage_scope": "national",
        "is_official": False,
    },
    {
        "name": "ANI",
        "kind": "rss",
        "base_url": "https://www.aninews.in",
        "feed_url": "https://aninews.in/rss/feed.xml",
        "credibility_tier": "tier_1",
        "coverage_scope": "national",
        "is_official": False,
    },
    {
        "name": "PTI",
        "kind": "html",
        "base_url": "https://www.ptinews.com",
        "feed_url": "",
        "credibility_tier": "tier_1",
        "coverage_scope": "national",
        "is_official": False,
    },
    {
        "name": "Telangana Today",
        "kind": "rss",
        "base_url": "https://telanganatoday.com",
        "feed_url": "https://telanganatoday.com/feed",
        "credibility_tier": "tier_1",
        "coverage_scope": "state",
        "is_official": False,
    },
    {
        "name": "Hans India",
        "kind": "rss",
        "base_url": "https://www.thehansindia.com",
        "feed_url": "https://www.thehansindia.com/rss/hyderabad",
        "credibility_tier": "tier_2",
        "coverage_scope": "local",
        "is_official": False,
    },
    {
        "name": "Deccan Chronicle",
        "kind": "rss",
        "base_url": "https://www.deccanchronicle.com",
        "feed_url": "https://www.deccanchronicle.com/rss_feed/",
        "credibility_tier": "tier_2",
        "coverage_scope": "local",
        "is_official": False,
    },
    {
        "name": "PIB",
        "kind": "rss",
        "base_url": "https://pib.gov.in",
        "feed_url": "https://pib.gov.in/RssMain.aspx?ModId=6&Lang=1&Regid=3",
        "credibility_tier": "official",
        "coverage_scope": "national",
        "is_official": True,
    },
    {
        "name": "GHMC",
        "kind": "html",
        "base_url": "https://www.ghmc.gov.in",
        "feed_url": "",
        "credibility_tier": "official",
        "coverage_scope": "local",
        "is_official": True,
    },
]
