# Generated by Django 4.2.11 on 2026-03-26 07:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNewsDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('local', 'Local'), ('global', 'Global')], max_length=20)),
                ('first_sent_at', models.DateTimeField(auto_now_add=True)),
                ('last_sent_at', models.DateTimeField(auto_now=True)),
                ('digest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_deliveries', to='alerts.alertdigest')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_deliveries', to='news.story')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_deliveries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_sent_at'],
                'unique_together': {('user', 'story')},
            },
        ),
    ]
