# Generated by Django 4.2.11 on 2026-03-26 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('kind', models.CharField(choices=[('rss', 'RSS'), ('api', 'API'), ('html', 'HTML')], max_length=20)),
                ('base_url', models.URLField()),
                ('feed_url', models.URLField(blank=True)),
                ('credibility_tier', models.CharField(choices=[('official', 'Official'), ('tier_1', 'Tier 1'), ('tier_2', 'Tier 2')], default='tier_1', max_length=20)),
                ('is_official', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('coverage_scope', models.CharField(choices=[('local', 'Local'), ('state', 'State'), ('national', 'National'), ('global', 'Global')], default='national', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('last_fetched_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
