# Generated by Django 4.2.11 on 2026-03-26 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='source',
            options={'ordering': ['name'], 'verbose_name': 'Trusted Source', 'verbose_name_plural': 'Trusted Sources'},
        ),
        migrations.AlterField(
            model_name='source',
            name='base_url',
            field=models.URLField(help_text='Canonical home page for the source.'),
        ),
        migrations.AlterField(
            model_name='source',
            name='coverage_scope',
            field=models.CharField(choices=[('local', 'Local'), ('state', 'State'), ('national', 'National'), ('global', 'Global')], default='national', help_text='Primary geography covered by this source.', max_length=20),
        ),
        migrations.AlterField(
            model_name='source',
            name='credibility_tier',
            field=models.CharField(choices=[('official', 'Official'), ('tier_1', 'Tier 1'), ('tier_2', 'Tier 2')], default='tier_1', help_text='Trust tier used when verifying stories.', max_length=20),
        ),
        migrations.AlterField(
            model_name='source',
            name='feed_url',
            field=models.URLField(blank=True, help_text='Feed or API endpoint used during ingestion.'),
        ),
        migrations.AlterField(
            model_name='source',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Inactive sources are skipped by ingestion jobs.'),
        ),
        migrations.AlterField(
            model_name='source',
            name='is_official',
            field=models.BooleanField(default=False, help_text='True for government or other official authorities.'),
        ),
        migrations.AlterField(
            model_name='source',
            name='kind',
            field=models.CharField(choices=[('rss', 'RSS'), ('api', 'API'), ('html', 'HTML')], help_text='How CrisisSync fetches content from this source.', max_length=20),
        ),
        migrations.AlterField(
            model_name='source',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Connector-specific settings or diagnostics.'),
        ),
        migrations.AlterField(
            model_name='source',
            name='name',
            field=models.CharField(help_text='Display name for the publication or authority.', max_length=120, unique=True),
        ),
    ]
